### ISSUE TITLE
Feature: Phone Number

### ISSUE THREAD

**Issue by Teyler7** [mattNit/Kavie#2]
It would be nice to have a validation for phone numbers. The regex Pattern is:
 ^(+\d{1,2}\s)?(?\d{3})?[\s.-]\d{3}[\s.-]\d{4}$

I found this pattern here.
https://stackoverflow.com/questions/16699007/regular-expression-to-match-standard-10-digit-phone-number/16699507#16699507

Not a bug, just would be nice for the next version :) I could even make a pull request for you if it would help you out all.

**Comment by matthewnitschke** [comment]
Closed in #4
