### ISSUE TITLE
small improvements

### ISSUE THREAD

**Issue by entraigas** [mattNit/Kavie#5]
Hi,

Just to bug you for 2 small improvements.
1). when opening the 'dist/kavie.js' & dist '/kavie.min.js', the version is still 0.5.0 (but it should be 0.6.0, right?)
2). finally, can you put an example of a custom validation rules (isYea for example).

Thanks man and great work.

**Comment by matthewnitschke** [comment]
Thanks for letting me know about the mismatch version numbers. I added a custom validator example of an even number implementation. Let me know if it doesn't make sense
