### ISSUE TITLE
Feature: add ajax validation support

### ISSUE THREAD

**Issue by entraigas** [mattNit/Kavie#7]
Hi, I wonder if it is possible to add support for ajax validation?
I tried to implement a validation for unique names like this:

```
Kavie.validatorFunctions.UniqueName = {
    validator: function (propValue, value) {
        var url = 'api/Customers/unique/' + value, retval;
        $.get(url, function (response) {
            retval = (response == 'true') ? true : false;
        });
        return retval;
    },
	message: "The customer Name is not unique"
};
```
but it didn't work because the ajax call is async. It means the `return retval;` line is executed before getting the the ajax call response, thus the return value (retval) of the function is undefined.

Also tried to use an ajax sync call, but it seem that's not supported anymore for some browsers...
The only workaround that I can think of, is to manually call the target.hasError() & target.errorMessage() function after getting the ajax response. But not sure how to do that...

Maybe calling a callback function that setup hasError & errorMessage observables when I get the response from the server.... but in that case I have to let Kavie knows that this is an async validator...

Hope you can add this feature.
Cheers!

**Comment by matthewnitschke** [comment]
I'll take a look at it. But in the meantime, have you tried `async: false` in the ajax options?

**Comment by entraigas** [comment]
Hi, yes but it's not supported by some browsers. Google Chrome give a warning about it and I think it run async anyway...
Thanks

**Comment by matthewnitschke** [comment]
Alright, so I have given some thought to it and I think I am going to add a `Kavie.isValidAsync` method. The method is going to return a javascript promise so you will use it as follows:

```javascript
self.submit = function(){
    Kavie.isValidAsync(self).then(function(isValid){
        if (isValid){
            console.log("All Good!");
        }
    }
}
```

The regular Kavie.isValid() won't change at all

It is going to take me a bit to write because I will have to rework the isValid method itself and figure out a way to bundle a lightweight js Promise polyfill

**Comment by matthewnitschke** [comment]
Ajax support added. Go [here](https://github.com/matthewnitschke/Kavie/wiki/Async-Validation) for documentation. Let me know if you have any troubles with it
