### ISSUE TITLE
Observable property passing in validators

### ISSUE THREAD

**Issue by Teyler7** [mattNit/Kavie#8]
Hey there, I made a custom validator and had this wonderful idea that I would be able to pass the property value of a knockout observable to the validator property of a observable using Kavie. Here is an example of what I wanted to accomplish: 

```javascript
self.maxReservations = ko.observable(7);

//maxCalc Validator in Kavie.
maxCalc: {
    validator: function (propVal, eleVal) {
        if (propVal && hasValue(eleVal)) {
            if (ko.unwrap(propVal) >= ko.unwrap(eleVal)) {
                return true;
            }
            return false;
        }
        else {
            return true;
        }
    },
    message: "Number must be less than or equal to {propVal}"
},
//Observable with Kavie attached
self.tickets = ko.observable().extend({
    trackChange: true,
    kavie: {
        apiAmpersand: true,
        required: true,
        maxCalc: maxReservations,
        section: "formData"
    }
});
```
So sadly this doesn't work, I was hoping it would take the observable property of maxReservations() that is constantly updating and use it for the maxCalc validator in self.tickets(), but I don't think it is built for that. I am going to look into it and I will send a pull request if I figure out a clean way to make it work. Thanks, man! I love all the hard work you are putting into this wonderful piece of software.

**Comment by matthewnitschke** [comment]
Ok, I as of v1.1.2 I have implemented this... sort of. You can pass  observables as properties but they don't update like you would think they would.

For example
```javascript
self.property = ko.observable(2);
self.value = ko.observable("a long value").extend({
	kavie: {
		maxLength: self.property
	}
});

if (!Kavie.isValid(self)){
	// Will go here because "a long value" has more characters than 2

	self.property(15);
	/*
	Once self.property(15) is set the view will still display that the view model is invalid
	You will need to call Kavie.isValid(self) again for it to be valid with the new property
	*/
}
```

The reason for this is to get the view to update when the property changes would require some significant library modifications, of which I am not willing to do for such a small feature. So what is above will work for now, and Ill leave it in.

Hope this somewhat solves your problem, sorry it couldn't be a better implementation

**Comment by Teyler7** [comment]
That is perfectly fine and should work great. I really really dig it! Thank you so much, this truly is a wonderful piece of code. Thank you for all your hard work.
